# Configuration du GBPBot
# ===================

# Configuration générale
general:
  log_level: "INFO"
  data_dir: "data"
  cache_dir: "cache"
  max_cache_size_mb: 100
  debug_mode: false

# Configuration des blockchains
blockchains:
  solana:
    enabled: true
    rpc_url: "https://api.mainnet-beta.solana.com"
    ws_url: "wss://api.mainnet-beta.solana.com"
    commitment: "confirmed"
  avalanche:
    enabled: true
    rpc_url: "https://api.avax.network/ext/bc/C/rpc"
    ws_url: "wss://api.avax.network/ext/bc/C/ws"
  sonic:
    enabled: false
    rpc_url: "https://rpc.sonic.fantom.network/"

# Configuration des wallets
wallets:
  solana:
    enabled: false
    keypair_path: ""
    public_key: ""
  avalanche:
    enabled: false
    private_key: ""
    address: ""
  sonic:
    enabled: false
    private_key: ""
    address: ""

# Configuration des modules
modules:
  arbitrage:
    enabled: true
    min_profit_percentage: 0.5
    max_slippage: 1.0
    gas_priority: "medium"
    max_concurrent_trades: 3
    dexes:
      - "traderjoe"
      - "pangolin"
      - "sushiswap"
  sniping:
    enabled: true
    max_buy_amount: 0.1
    min_liquidity: 10000
    max_tax_percentage: 5.0
    auto_sell: true
    take_profit_percentage: 50.0
    stop_loss_percentage: 10.0
    blockchains:
      - "solana"
      - "avalanche"
  auto_trader:
    enabled: false
    risk_level: "medium"
    allocation:
      arbitrage: 0.5
      sniping: 0.3
      hold: 0.2

# Configuration de l'IA
ai:
  enabled: true
  provider: "auto"
  openai:
    api_key: ""
    model: "gpt-3.5-turbo"
  llama:
    model_path: "models/llama-7b-q4"
    quantization: "4bit"
  local_models:
    enabled: true
    models_dir: "models"
    max_memory_usage_mb: 2000

# Configuration des notifications
notifications:
  console:
    enabled: true
    verbose: true
    colors: true
  telegram:
    enabled: false
    token: ""
    chat_id: ""
    include_data: true
    notify_on:
      - trade
      - error
      - warning
  file:
    enabled: true
    path: "logs/notifications.log"
    max_size_mb: 10
    rotate: true
    backups: 5

# Configuration des plateformes d'échange centralisées (CEX)
exchanges:
  binance:
    enabled: true
    api_key: ""
    api_secret: ""
    testnet: false
    rate_limits:
      requests_per_second: 10
      requests_per_minute: 1200
  kucoin:
    enabled: false
    api_key: ""
    api_secret: ""
    passphrase: ""
    testnet: false
    rate_limits:
      requests_per_second: 5
      requests_per_minute: 300
  gate:
    enabled: false
    api_key: ""
    api_secret: ""
    testnet: false
    rate_limits:
      requests_per_second: 5
      requests_per_minute: 300

# Configuration de l'arbitrage
arbitrage:
  cex_dex:
    enabled: true
    auto_execute: false
    min_profit_percentage: 0.5
    max_trade_amount: 100.0
    check_interval: 5
    cex:
      - "binance"
    dex:
      - "solana"
      - "avalanche"
      - "sonic"
    pairs:
      - "BTC/USDT"
      - "ETH/USDT"
      - "SOL/USDT"
      - "AVAX/USDT"
    pair_configs:
      - pair: "BTC/USDT"
        amount: 0.01
      - pair: "ETH/USDT"
        amount: 0.1
      - pair: "SOL/USDT"
        amount: 1.0
      - pair: "AVAX/USDT"
        amount: 1.0
    token_addresses:
      solana:
        BTC: "9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E"  # BTC (Solana)
        ETH: "2FPyTwcZLUg1MDrwsyoP4D6s1tM7hAkHYRjkNb5w6Pxk"  # ETH (Solana)
        SOL: "So11111111111111111111111111111111111111112"   # SOL (Solana)
        USDT: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB" # USDT (Solana)
      avalanche:
        BTC: "0x152b9d0FdC40C096757F570A51E494bd4b943E50"    # BTC.b (Avalanche)
        ETH: "0x49D5c2BdFfac6CE2BFdB6640F4F80f226bc10bAB"    # WETH.e (Avalanche)
        AVAX: "0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7"   # WAVAX (Avalanche)
        USDT: "0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7"   # USDT (Avalanche)
      sonic:
        BTC: "0x321162Cd933E2Be498Cd2267a90534A804051b11"    # BTC (Fantom)
        ETH: "0x74b23882a30290451A17c44f4F05243b6b58C76d"    # ETH (Fantom)
        FTM: "0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83"    # WFTM (Fantom)
        USDT: "0x049d68029688eAbF473097a2fC38ef61633A3C7A"   # USDT (Fantom)
