blockchains:
  avalanche:
    enabled: true
    rpc:
      providers:
      - url: https://api.avax.network/ext/bc/C/rpc
        weight: 1.0
    tokens:
      USDC: '0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E'
      USDT: '0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7'
      WAVAX: '0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7'
strategies:
  arbitrage:
    blockchain: avalanche
    enabled: true
    pairs:
    - - WAVAX
      - USDC
    - - WAVAX
      - USDT
    - - USDC
      - USDT
    settings:
      gas_boost: 1.2
      max_slippage: 1.0
      min_profit_threshold: 0.5
