name: Code Analysis

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 1'  # Exécuter l'analyse complète tous les lundis à minuit

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Analyser tout l'historique pour un meilleur suivi
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python
          config-file: .github/codeql/codeql-config.yml
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
  
  python-analysis:
    name: Python Static Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-core.txt
          pip install bandit pylint ruff safety
      
      - name: Run Bandit
        run: bandit -r . -x venv,venv_310,venv_new,env -f sarif -o bandit-results.sarif
        continue-on-error: true
      
      - name: Run Pylint
        run: pylint --output-format=colorized gbpbot || true
      
      - name: Run Ruff
        run: ruff check --output-format=github .
        continue-on-error: true
      
      - name: Run Safety
        run: safety check -r requirements-core.txt --full-report || true
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: bandit-results.sarif 